// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * OpenConfigFile finds the default file or asks the user to select one, then
 * returns its path and contents. Parsing and editing remain in the frontend by now.
 */
export function OpenConfigFile(): $CancellablePromise<$models.ConfigFile | null> {
    return $Call.ByID(1176887371);
}
