// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateConfigFile validates a new document and creates it at the requested path.
 */
export function CreateConfigFile(path: string, configuration: $models.Configuration, overwrite: boolean): $CancellablePromise<$models.ConfigFile | null> {
    return $Call.ByID(539612519, path, configuration, overwrite);
}

/**
 * OpenConfigFile finds the default file or asks the user to select one, then
 * returns its path and raw contents. Parsing and editing are deliberately not
 * part of this first loading step.
 */
export function OpenConfigFile(): $CancellablePromise<$models.ConfigFile | null> {
    return $Call.ByID(1176887371);
}

/**
 * OpenConfigFileAtPath loads a configuration dropped onto the application window.
 */
export function OpenConfigFileAtPath(path: string): $CancellablePromise<$models.ConfigFile | null> {
    return $Call.ByID(2068630133, path);
}

/**
 * OpenTemplate loads the official server template as a new, unsaved document.
 */
export function OpenTemplate(): $CancellablePromise<$models.ConfigFile | null> {
    return $Call.ByID(3590655485);
}

/**
 * SaveConfiguration validates and saves all editable configuration fields.
 */
export function SaveConfiguration(path: string, configuration: $models.Configuration): $CancellablePromise<void> {
    return $Call.ByID(389537572, path, configuration);
}

/**
 * SelectConfigDestination opens the native dialog used for a new configuration.
 */
export function SelectConfigDestination(): $CancellablePromise<string> {
    return $Call.ByID(2401293339);
}

/**
 * SelectConfigFile always opens the native picker, even when a default file
 * exists. It is used when the user explicitly wants another configuration.
 */
export function SelectConfigFile(): $CancellablePromise<$models.ConfigFile | null> {
    return $Call.ByID(962140871);
}
