// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AnnouncementConfig {
    "Enabled": boolean;
    "Multicast": boolean;
    "Port": number;
    "MulticastGroup": string;
}

/**
 * ConfigFile is the bridge between Go and the React editor.
 */
export interface ConfigFile {
    "path": string;
    "content": string;
    "config": Configuration | null;
    "validationErrors": ValidationError[] | null;
}

export interface Configuration {
    "Log": boolean;
    "GeneratePlatformUserId": boolean;
    "Authentication": string;
    "Games": GamesConfiguration;
    "Announcement": AnnouncementConfig;
}

export interface GameConfig {
    "Hosts": string[] | null;
}

export interface GamesConfiguration {
    "Enabled": string[] | null;
    "age1": GameConfig;
    "age2": GameConfig;
    "age3": GameConfig;
    "age4": GameConfig;
    "athens": GameConfig;
}

export interface ValidationError {
    "field": string;
    "message": string;
}
