// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigFile is the small bridge between Go and the React editor.
 */
export interface ConfigFile {
    "path": string;
    "content": string;
}
